baseURL: "https://nectarition.jp"
languageCode: "ja-JP"
title: "ねくたりしょん / Nectarition"

params:
  defaultDescription: "いろいろやります、ねくたりしょん。"
  author: "Nectarition"
  authorPersonalName: "染宮ねいろ"
  logo: "/logo.png"
  card: "/card.jpg"
  mainSections:
    - posts

taxonomies:
  department: "departments"

menu:
  main:
    - name: "ABOUT"
      weight: 1
      identifier: "about"
      url: "/about/"
    - name: "LEADER"
      weight: 10
      identifier: "leader"
      url: "/leader/"
    - name: "WORKS"
      weight: 20
      identifier: "works"
      url: "/works/"
    - name: "POSTS"
      weight: 30
      identifier: "posts"
      url: "/posts/"
    - name: "Nectari-Co"
      weight: 40
      identifier: "nectari-co"
      url: "/nectari-co/"
    - name: "CONTACTS"
      weight: 50
      identifier: "contacts"
      url: "/contacts/"
    - name: "NOTE"
      weight: 60
      identifier: "note"
      url: "https://note.com/nectarition"
