baseURL: 'https://nectarition.jp'
languageCode: 'ja-JP'
title: 'ねくたりしょん / Nectarition'

params:
  author: 'Nectarition'
  authorPersonalName: '染宮ねいろ'
  logo: 'logo.png'
  card: 'card.jpg'

taxonomies:
  department: 'departments'

menu:
  main:
    - name: 'ABOUT'
      weight: 1
      identifier: 'about'
      url: '/about/'
    - name: 'WORKS'
      weight: 10
      identifier: 'works'
      url: '/works/'
    - name: 'POSTS'
      weight: 20
      identifier: 'posts'
      url: '/posts/'
    - name: 'CONTACTS'
      weight: 30
      identifier: 'contacts'
      url: '/contacts/'
